### ISSUE TITLE
Data Architecture

### ISSUE THREAD

**Issue by dholloran-ample** [ample/dev-playbook#15]
**Doc:** `code/data-architecture/README.md`

- Working with Headless CMS products
- Naming conventions
- Building, storing, and sharing schema
- Blocks, containers

**Comment by seancdavis** [comment]
I like this and think we should keep it here. May change the title of it. I'm thinking it has a lot to do with how we architect the CMS and then the process by which that schema maps to components and their properties.

**Comment by seancdavis** [comment]
@dholloran-ample I started writing this. I wanted to provide an intro into headless CMS products. And then I started thinking about the process of choosing the right one and what our recommendation is.

But that has parallels to other decisions we make along the way. So, as part of this task, I'm spinning up another page in the _Work_ section on choosing the right tools. I'll only add the CMS commentary at this time.

Should we have another issue to track the completion of the tools page? Do you think the choosing tools page is a good idea?
