### ISSUE TITLE
Code Landing

### ISSUE THREAD

**Issue by dholloran-ample** [ample/dev-playbook#16]
**Doc:** `code/README.md`

- Convention over configuration
- Semantic code — write for someone else

**Comment by seancdavis** [comment]
Wondering if this makes sense to combine with #18 and use as the landing page. Seems like it could be a nice lead in to the section. Otherwise, we could keep it separate and the landing page could be an overview of the other pages in the section.

What do you think, @dholloran-ample?

**Comment by dholloran-ample** [comment]
@seancdavis I like that idea we can always separate it if need be. I'll go ahead and tweak the files and issues.
